# Generated by Django 4.0.4 on 2022-04-14 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('P', 'Purple'), ('Y', 'Yellow')], default='R', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField(auto_now_add=True)),
                ('priority', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('Y', 'Yellow')], default='G', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('due_date', models.DateTimeField(blank=True)),
                ('completed', models.DateField(blank=True)),
                ('priority_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.priority')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TodoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.category')),
                ('todo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.todo')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('start', models.DateField(blank=True)),
                ('end', models.DateField(blank=True)),
                ('all_day', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
