# Generated by Django 4.0.4 on 2022-04-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='todos.category'),
            preserve_default=False,
        ),
    ]
