# Generated by Django 4.0.4 on 2022-04-15 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_todo_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category_id',
            field=models.ForeignKey(default='Personal', on_delete=django.db.models.deletion.CASCADE, to='todos.category'),
        ),
    ]
